#!/bin/bash

set -e

STATUS=0

echo "Running pyright"
rye run pyright replicate || STATUS=$?
echo ""

echo "Running pylint"
rye run pylint --exit-zero replicate || STATUS=$?
echo ""

echo "Running rye lint"
rye lint . || STATUS=$?
echo ""

echo "Running rye fmt --check"
rye fmt --check || STATUS=$?
echo ""

exit $STATUS
